add git

diff --git a/zsh/.zsh/func b/zsh/.zsh/func
--- a/zsh/.zsh/func
+++ b/zsh/.zsh/func
@@ -107,6 +107,24 @@ function set_cur_os() {
     unset GOGOSING
 }
 
+function openpr() {
+  github_url=`git remote -v | awk '/fetch/{print $2}' | sed -Ee 's#(git@|git://)#https://#' -e 's@com:@com/@' -e 's%\.git$%%' | awk '/github/'`;
+  branch_name=`git symbolic-ref HEAD | cut -d"/" -f 3,4`;
+  pr_url=$github_url"/compare/main..."$branch_name
+  open $pr_url;
+}
+ 
+# Run git push and then immediately open the Pull Request URL
+function gpr() {
+  git push origin HEAD
+ 
+  if [ $? -eq 0 ]; then
+    openpr
+  else
+    echo 'failed to push commits and open a pull request.';
+  fi
+}
+
 function bojlogin() {
     mkdir -p $HOME/.boj-cli
     touch $HOME/boj-handle
